#!/bin/bash
set -e
cd "$(dirname "$0")"

# generated by ChatGPT

ENV_DIR=".venv"
MAIN="package/main.py"

PY_CMD=""

# ----------------------------
# 1. Try Python 3.12 specifically
# ----------------------------
if command -v python3 >/dev/null 2>&1; then
    VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    echo "Found python3 version $VERSION"

    if [[ "$VERSION" == 3.12* ]]; then
        PY_CMD="python3"
    fi
fi

# ----------------------------
# 2. Fallback to python (if exists)
# ----------------------------
if [ -z "$PY_CMD" ] && command -v python >/dev/null 2>&1; then
    VERSION=$(python --version 2>&1 | awk '{print $2}')
    echo "Found python version $VERSION"

    PY_CMD="python"
fi

# ----------------------------
# 3. No Python found
# ----------------------------
if [ -z "$PY_CMD" ]; then
    echo "Python not found on system."
    echo "Please install Python 3.12"
    exit 1
fi

# ----------------------------
# Create venv if missing
# ----------------------------
if [ ! -f "$ENV_DIR/bin/python" ]; then
    echo "Creating virtual environment..."
    "$PY_CMD" -m venv "$ENV_DIR"

    "$ENV_DIR/bin/python" -m pip install --upgrade pip
fi

# ----------------------------
# Install dependencies
# ----------------------------
"$ENV_DIR/bin/python" -m pip install -q -r requirements.txt

# ----------------------------
# Run program
# ----------------------------
"$ENV_DIR/bin/python" "$MAIN"