@echo off
cd /d "%~dp0"

set "ENV_DIR=.venv"

set "MAIN=package\main.py"

REM generated by ChatGPT

REM ----------------------------
REM 1. Try Python launcher (best case)
REM ----------------------------
py -3.12 --version >nul 2>&1
if %errorlevel%==0 (
    set "PY_CMD=py -3.12"
    goto :create_venv
)

REM ----------------------------
REM 2. Try plain python
REM ----------------------------
python --version >nul 2>&1
if %errorlevel%==0 (
    for /f "tokens=2" %%v in ('python --version') do set VERSION=%%v

    echo Found Python %VERSION%

    REM WARNING ONLY (cannot reliably enforce version here)
    set "PY_CMD=python"
    goto :create_venv
)

REM ----------------------------
REM 3. Nothing found
REM ----------------------------
echo Python not found on system.
echo Please install Python 3.12 from https://python.org
exit /b 1

:create_venv
echo Using: %PY_CMD%

if not exist "%ENV_DIR%\Scripts\python.exe" (
    echo Creating virtual environment...
    %PY_CMD% -m venv "%ENV_DIR%"
)

"%ENV_DIR%\Scripts\python" -m pip install --upgrade pip
"%ENV_DIR%\Scripts\python" -m pip install -r requirements.txt

"%ENV_DIR%\Scripts\python" package\main.py