import sqlite3
import config
import utils
from pathlib import Path
from query import *

class Issue:
    def __init__(self, issue_id, issue_summary, issue_description):
        self.id = issue_id
        self.summary = issue_summary or ""
        self.description = issue_description or ""

    def to_text(self):
        return f"{self.summary}. {self.description}".strip()

    def __eq__(self, other):
        if isinstance(other, Issue):
            return self.id == other.id
        return False

    def __hash__(self):
        return hash(self.id)
    
    def __repr__(self):
        return self.to_text()

class Commit:
    def __init__(self, hash, message):
        self.hash = hash
        self.message = message

    def __eq__(self, other):
        if isinstance(other, Commit):
            return self.hash == other.hash
        return False

    def __hash__(self):
        return hash(self.hash)
    
    def __repr__(self):
        return f"{self.message}"

# This class was generated by ChatGPT
class DotRow(sqlite3.Row):
    """
    Allows rows to be acccessed using dot syntax
    """
    def __getattr__(self, item):
        return self[item]

class SEOSS33:
    """
    A convenience class that handles database connections and provides 
    SEOSS 33 specific methods. It allows access to one project defined as a constructor parameter. 

    Attributes:
        definition: the schema of the SEOSS33 dataset in the form of a list of table names that are part of the schema
    """
    def __init__(self, db_files):
        """
        db: A list of paths to .sqlite3 files provided by the SEOSS 33 database 
        """
        self.name = Path(db_files).stem
        self.conn = sqlite3.connect(db_files)
        self.conn.row_factory = DotRow
        self.cursor = self.conn.cursor()
        self.definition = self._generate_definition()

        self.issues, self.commits, self.links = self._load()

    def _generate_definition(self):
        self.cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        keys = [col.name for col in self.cursor]
        return f"Keys: {keys}"

    def meta_table_definition(self, name):
        return self.cursor.execute(f"PRAGMA table_info({name});")
    
    def query(self, query: str, params=None) -> tuple[list[DotRow], list[str]]:
        """
        Executes the SQL query.
        Returns list of rows and a list of the keys/column names of the resulting rows.
        """
        if params != None:
           result = self.cursor.execute(query, params)
        else:
            result = self.cursor.execute(query)

        return result.fetchall(), [col[0] for col in result.description]
    
    def _load(self):
        trace_links, _ = self.query(SELECT_ALL_TRACE_LINKS)

        issues = {}
        commits = {}
        links = {}
        valids = 0
        for link in trace_links:
            issue = Issue(link.issue_id, link.summary, link.description)
            commit = Commit(link.commit_hash, link.message)
            issues[link.issue_id] = issue
            commits[link.commit_hash] = commit

            if utils.str_as_date(link.created_date) <= utils.str_as_date(link.committed_date):
                links.setdefault(commit, set()).add(issue)
                valids += 1
        # print(f"Loaded {self.name}: {100*valids/len(trace_links):.2f}% links valid")
        return issues, commits, links
    
    def get_issues(self):
        return list(self.issues.values())
    
    def get_commits(self):
        return list(self.commits.values())
    
    def get_trace_links(self) -> dict[Commit, set[Issue]]:
        return self.links.items()
    
    def close(self):
        self.conn.close()

def init_db():
    """
    The caller is expected to call SEOSS33.close() to close the database connection when it is no longer needed
    """
    DB_ROOT, DB_ZIP_PATH = config.init_config()
    SEOSS_PATH = DB_ROOT / "seoss33"
    
    if not Path.exists(SEOSS_PATH):
        utils.unzip(DB_ZIP_PATH, SEOSS_PATH)

    bz2_files = list(SEOSS_PATH.glob("*.bz2"))
    for file in bz2_files:
        utils.decompress_bz2(file)

    sqlite_files = list(SEOSS_PATH.glob("*.sqlite3"))
    print(f"SEOSS 33 dataset loaded successfully: Detected {len(sqlite_files)} project databases")
    
    return sqlite_files