import sqlite3
import config
import utils
from pathlib import Path

# This class was generated by ChatGPT
class DotRow(sqlite3.Row):
    """
    Allows rows to be acccessed using dot syntax
    """
    def __getattr__(self, item):
        return self[item]

class SEOSS33:
    """
    A convenience class that handles database connections and provides 
    SEOSS 33 specific methods. It allows access to one project defined as a constructor parameter. 

    Attributes:
        definition: the schema of the SEOSS33 dataset in the form of a list of table names that are part of the schema
    """
    def __init__(self, db):
        """
        db: An absolute path to one of the .sqlite3 files provided by the SEOSS 33 database 
        """
        self.conn = sqlite3.connect(db)
        self.conn.row_factory = DotRow
        self.cursor = self.conn.cursor()
        self.definition = self._generate_definition()

    def _generate_definition(self):
        self.cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        keys = [col.name for col in self.cursor]
        return f"Keys: {keys}"

    def meta_table_definition(self, name):
        return self.cursor.execute(f"PRAGMA table_info({name});")
    
    def query(self, query: str, params=None) -> tuple[list[DotRow], list[str]]:
        """
        Executes the SQL query.
        Returns list of rows and a list of the keys/column names of the resulting rows.
        """
        if params != None:
           result = self.cursor.execute(query, params)
        else:
            result = self.cursor.execute(query)

        return result.fetchall(), [col[0] for col in result.description]
    
    def close(self):
        self.conn.close()

def init_db():
    """
    The caller is expected to call SEOSS33.close() to close the database connection when it is no longer needed
    """
    DB_ROOT, DB_ZIP_PATH = config.init_config()
    SEOSS_PATH = DB_ROOT / "seoss33"
    
    if not Path.exists(SEOSS_PATH):
        utils.unzip(DB_ZIP_PATH, SEOSS_PATH)

    bz2_files = list(SEOSS_PATH.glob("*.bz2"))
    for file in bz2_files:
        utils.decompress_bz2(file)

    sqlite_files = list(SEOSS_PATH.glob("*.sqlite3"))
    print(f"SEOSS 33 dataset loaded successfully: Detected {len(sqlite_files)} project databases")
    
    return SEOSS33(sqlite_files[0])