from pathlib import Path
from llm import example_llm
from similarity_model import RETRIEVER_NAMES, Retriever, build_retriever
from config import *
from utils import *
from db import *
from query import *

def get_candidate_issues(model: Retriever, commit: Commit, topk=None) -> list[Issue]:
    candidates = model.get_relevant_issues(commit.message)
    if topk != None:
        return candidates[:topk]
    return candidates


def compute_recall_k(pred_issues: list[Issue], true_issues: list[Issue], k=None) -> float:
    pred_issues = set(pred_issues[:k]) if k != None else set(pred_issues)
    true_issues = set(true_issues)

    count = 0
    for issue in true_issues:
        if issue in pred_issues:
            count += 1
        
    recall = count/len(true_issues)
    "TODO: Plot recall@k over multiple k values to get a curve showing how recall changes at different k's. Ideally it is just 1 but realistically probably looks like an increasing curve"
    return recall

def compute_recall_curv_old(pred_issues: list[Issue], true_issues: list[Issue], ks=None) -> float:
    if ks == None:
        ks = [1] + list(range(5, 101, 5))

    recalls = {}
    for k in ks:
        recalls[k] = compute_recall_k(pred_issues, true_issues, k=k)
    return recalls

def compute_recall_curve(pred_issues, true_issues):
    """
    Faster recall computation generated by ChatGPT.
    """
    true_set = set(true_issues)

    recalls = {}
    found = 0

    for i, issue in enumerate(pred_issues, start=1):
        if issue in true_set:
            found += 1
  
        recalls[i] = found / len(true_set)

    return recalls

def get_ranked_issues(model, commit, issues):
    ranked_issues = model(commit, issues)
    return ranked_issues

def compute_precision_curve(pred_issues, true_issues):
    true_set = set(true_issues)

    precisions = {}
    found = 0

    for i, issue in enumerate(pred_issues, start=1):
        if issue in true_set:
            found += 1

        precisions[i] = found / i

    return precisions

def preprocess(seoss33: SEOSS33):
    # Gets issues and commits that have trace link
    trace_links, keys = seoss33.query(SELECT_ALL_TRACE_LINKS)
    print(f"Trace link keys: {keys}\n")

    # Extract issue ids for all issues that are linked to merge commits
    count = 0
    issue_ids = []
    for link in trace_links:
        if link.is_merge:
            count += 1
            issue_ids.append(link.issue_id)

    # Get all trace links for issues that were linked to a merge commit
    placeholders = ",".join(["?"] * len(issue_ids))
    issues, keys = seoss33.query(f"select * from change_set_link where issue_id in ({placeholders})", params=issue_ids)
    print(f"Issue keys: {keys}")
    
    # Count trace links for issues that were linked to a merge commit
    issue_counts = {}
    for issue in issues:
        issue_counts[issue.issue_id] = issue_counts.get(issue.issue_id, 0) + 1
    print(f"Commit count per issue: {issue_counts}")

    # Count how many trace links for these issues were merge commits
    issue_commits = {}
    for link in trace_links:
        if link.is_merge:
            issue_commits[link.issue_id] = issue_commits.get(link.issue_id, 0) + 1
    print(f"Merge commit count per issue: {issue_commits}")

    print("The issues that have only one linked commit and have one merge commit need to be investigated to see how that merge commit resolved the issue and wether they should be included in the experiment")

def commit_counts(seoss33: SEOSS33):
    trace_links, keys = seoss33.query(SELECT_ALL_TRACE_LINKS)
    print(f"Trace link keys: {keys}\n")

    commit_counts = {}
    for link in trace_links:
        commit_counts[link.commit_hash] = commit_counts.get(link.commit_hash, 0) + 1

    for c, count in commit_counts.items():
        if count > 5:
            print(f"Issues per commit: {count} ({c})")

def evaluate_retriever(retriever: Retriever, seoss33: SEOSS33) -> float:
    """
    Average per-commit recall over all trace links in the loaded project DB.

    @param retriever: Configured first-stage model (issues indexed at build time).
    @param seoss33: Open SEOSS33 dataset handle.
    @return: Mean recall over entire test set.
    """

    recalls_per_commit = []
    precisions_per_commit = []
    trace_links = list(seoss33.get_trace_links())
    total = len(trace_links)
    for i, (commit, issues) in enumerate(trace_links, start=1):
        candidate_issues = get_candidate_issues(retriever, commit, topk=100)
        recall_curve = compute_recall_curve(candidate_issues, issues)
        precision_curve = compute_precision_curve(candidate_issues, issues)
        recalls_per_commit.append(recall_curve)
        precisions_per_commit.append(precision_curve)
        print(f"Testing...{i / total * 100:.2f}%\r", end="")
    print()

    recalls_k = {} 
    precisions_k = {}
    for recall_curve, precision_curve in zip(recalls_per_commit, precisions_per_commit):
        for k, recall in recall_curve.items():
            recalls_k.setdefault(k, []).append(recall)
            precisions_k.setdefault(k, []).append(precision_curve[k])

    
    average_recalls_k = {}
    
    for k, recalls in recalls_k.items():
        average_recall = sum(recalls)/len(recalls)
        average_recalls_k[k] = average_recall
        # if k in [1, 5, 10, 20, 50, 100]:
        #     print(f"Recall@{k}: {average_recall:.4f}", end=" | ")

    average_precisions_k = {}
    for k, precisions in precisions_k.items():
        average_precision = sum(precisions)/len(precisions)
        average_precisions_k[k] = average_precision
        # if k in [1, 5, 10, 20, 50, 100]:
            # print(f"Recall@{k}: {average_recall:.4f}", end=" | ")

    return average_recalls_k, average_precisions_k


if __name__ == "__main__":
    # Compare all four retrieval backends on the same issue corpus and trace links.
    seoss33 = init_db()

    recalls_across_projects = {}
    precisions_across_projects = {}
    for project in seoss33:
        issues = project.get_issues()

        print(f"Evaluating {len(RETRIEVER_NAMES)} retrieval techniques on {len(issues)} issues from {project.name}\n")

        retriever_recalls = {}
        retriever_precisions = {}
        for name in RETRIEVER_NAMES:
            print(f"--- {name} ---")
            print("Building retriever (download/load/encode as needed)...")
            retriever = build_retriever(name, issues)
            if hasattr(retriever, "device"):
                print(f"Ready | Device: {retriever.device}")
            else:
                print("Ready")
            average_recalls, average_precisions = evaluate_retriever(retriever, project)
            mean_recall = sum(average_recalls.values())/len(average_recalls.values())
            retriever_recalls[name] = average_recalls
            retriever_precisions[name] = average_precisions
            # plot(average_recalls)
        
        recalls_across_projects[project.name] = retriever_recalls
        precisions_across_projects[project.name] = retriever_precisions
    plot_projects(recalls_across_projects, precisions_across_projects)

    # get_ranked_issues()
    # compute_precision_k()

    for project in seoss33:
        project.close()