import bz2
import shutil
import zipfile
import matplotlib.pyplot as plt
from pathlib import Path
import json
import re
import numpy as np
from datetime import datetime

from config import DATA_DIR
RECALL_DATA_PREFIX = "recall_data"
PRECISION_DATA_PREFIX = "precision_data"


# ---------------------------------------------------
# DateTime Utilities
# ---------------------------------------------------

def str_as_date(ts: str) -> datetime:
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))

# ---------------------------------------------------
# Exrtaction Utilities
# ---------------------------------------------------

def decompress_bz2(in_path, out_path=None, keep=False):
    if out_path is None:
        out_path = in_path.with_suffix("")

    print(f"Decompressing {in_path.parent.name}/{in_path.name} → {out_path.parent.name}/{out_path.name}")
    with bz2.open(in_path, "rb") as src, open(out_path, "wb") as dst:
        shutil.copyfileobj(src, dst)

    if not keep:
        in_path.unlink()
    
def unzip(in_path, out_path):
    print(f"Extracting {in_path.parent.name}/{in_path.name} → {out_path.parent.name}/{out_path.name}")
    with zipfile.ZipFile(in_path, "r") as zip_ref:
        zip_ref.extractall(out_path)


# ---------------------------------------------------
# Data Utilities
# ---------------------------------------------------

def get_latest_data_file_index(prefix: str):
    """
    Returns the highest x value from files in the data directory that are named <prefix_000x>
    """
    pattern = re.compile(rf"{re.escape(prefix)}_(\d+)\..+")

    max_idx = None

    for file in Path(DATA_DIR).iterdir():
        match = pattern.match(file.name)
        if match:
            idx = int(match.group(1))
            max_idx = idx if max_idx is None else max(max_idx, idx)

    return max_idx

def get_latest_data_file(prefix: str):
    idx = get_latest_data_file_index(prefix)
    if idx is None:
        raise FileNotFoundError()
    return DATA_DIR / f"{prefix}_{idx:04d}.file"

def get_next_data_file(prefix: str):
    idx = get_latest_data_file_index(prefix)
    if idx is None:
        idx = -1
    return DATA_DIR / f"{prefix}_{idx+1:04d}.file"

def save_dict(data: dict, name: str):
    data_path = get_next_data_file(name)
    with open(data_path, "w") as f:
        json.dump(data, f)

def load_dict(name: str):
    data_path = get_latest_data_file(name)
    with open(data_path, "r") as f:
        return json.load(f)

def save_recalls_data(recalls: dict):
    save_dict(recalls, RECALL_DATA_PREFIX)

def save_precision_data(recalls: dict):
    save_dict(recalls, PRECISION_DATA_PREFIX)

def load_recall_data():
    return load_dict(RECALL_DATA_PREFIX)

def load_precision_data():
    return load_dict(PRECISION_DATA_PREFIX)


# ---------------------------------------------------
# Plotting Utilities
# ---------------------------------------------------

def plot_bars(data, title="", xlabel="", ylabel=""):
    """
    Generated by ChatGPT
    """
    projects = list(data.keys())
    retrievers = list(next(iter(data.values())).keys())

    x = np.arange(len(projects))  # project positions
    bar_width = 0.2

    fig, ax = plt.subplots(figsize=(12, 6))
    for i, retriever in enumerate(retrievers):
        values = [data[p][retriever] for p in projects]

        ax.bar(
            x + i * bar_width,
            values,
            width=bar_width,
            label=retriever
        )

    ax.set_xticks(x + bar_width * (len(retrievers) - 1) / 2)
    ax.set_xticklabels(projects, rotation=30, ha="right")

    ax.set_ylabel(ylabel)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    ax.legend()

    plt.tight_layout()
    plt.show()

def get_metric_at_k(metrics, k):
    """
    Generated by ChatGPT
    """
    data = {}
    for project, retrievers in metrics.items():
        data[project] = {
            retriever: metrics[str(k)]
            for retriever, metrics in retrievers.items()
        }
    return data

def plot_recall_bars(recalls, k):
    data = get_metric_at_k(recalls, k)
    title = f"Recall@{k} across projects and retrievers"
    xlabel = "Projects"
    ylabel = f"Recall@{k}"
    plot_bars(data, title=title, xlabel=xlabel, ylabel=ylabel)

def plot_precision_bars(precisions, k):
    data = get_metric_at_k(precisions, k)
    title = f"Precision@{k} across projects and retrievers"
    xlabel = "Projects"
    ylabel = f"Precision@{k}"
    plot_bars(data, title=title, xlabel=xlabel, ylabel=ylabel)

def plot_average_bars(data, title="", xlabel="", ylabel=""):
    labels = list(data.keys())
    values = list(data.values())
    x = np.arange(len(labels))
    bar_width = 0.2

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.bar(x, values)
        
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right")

    ax.set_ylabel(ylabel)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    ax.legend()

    plt.tight_layout()
    plt.show()

def get_metric_by_retriever(metrics: dict, k):
    data = {}
    for _, retrievers in metrics.items(): 
        for retriever, values in retrievers.items():
            data.setdefault(retriever, []).append(values[str(k)])

    for retriever, values in data.items():
        data[retriever] = sum(values)/len(metrics)

    return data

def plot_average_recall_bars(recalls: dict, k):
    data = get_metric_by_retriever(recalls, k)
    title = f"Recall@{k} across projects"
    xlabel = "Projects"
    ylabel = f"Recall@{k}"
    plot_average_bars(data, title=title, xlabel=xlabel, ylabel=ylabel)

def plot_average_precision_bars(precisions: dict, k):
    data = get_metric_by_retriever(precisions, k)
    title = f"Precision@{k} across projects"
    xlabel = "Projects"
    ylabel = f"Precisions@{k}"
    plot_average_bars(data, title=title, xlabel=xlabel, ylabel=ylabel)

def plot(ax, x, label=""):
    ax.plot(range(len(x)), x, label=label)
    return ax

def plot_retrievers(axis, retrievers:dict, title="", xlabel="", ylabel=""):
    for retriever, metric in retrievers.items():
        plot(axis, metric.values(), label=retriever)
    axis.legend()
    axis.set_xlabel(xlabel)
    axis.set_ylabel(ylabel)
    axis.set_title(title)
    return axis

def plot_projects(recalls: dict, precisions: dict):
    fig, axs = plt.subplots(6, 6, figsize=(18, 18))
    for i, (project, _) in enumerate(recalls.items()): 
        row = i // 6
        col = i % 6
        plot_retrievers(axs[row][col], recalls[project], title=project, xlabel="K", ylabel="Recall")
    plt.show()

    fig, axs = plt.subplots(6, 6, figsize=(18, 18))
    for i, (project, _) in enumerate(precisions.items()):
        row = i // 6
        col = i % 6
        plot_retrievers(axs[row][col], precisions[project], title=project, xlabel="K", ylabel="Precision")
    plt.show()

def plot_project_link_percent(orientation="vertical"):
    projects = [
        "Archiva", "Axis2", "Cassandra", "Derby", "Drools",
        "Erray", "Flink", "Groovy", "Hadoop", "HBase",
        "Hibernate", "Hive", "Hornetq", "Infinispan", "Izpack",
        "JBehave", "JBoss T.M.", "JBPM", "Kafka", "Keycloak",
        "Log4j", "Lucene", "Maven", "Pig", "Railo",
        "Restasy", "Seam2", "Spark", "Switchyard", "Teiid",
        "Weld", "WildFly", "Zookeeper"
    ]

    values = [
        26.42, 18.93, 37.03, 83.17, 47.24,
        8.11, 41.98, 37.91, 97.13, 90.06,
        82.20, 96.34, 19.37, 68.55, 30.73,
        46.53, 71.64, 22.06, 63.17, 51.73,
        32.13, 63.12, 24.10, 92.85, 24.36,
        34.77, 25.88, 61.72, 80.29, 72.38,
        30.45, 57.71, 87.12
    ]

    if orientation == "horizontal":
        plt.figure(figsize=(10, 10))

        y_pos = range(len(projects))

        bars = plt.barh(y_pos, values)
        plt.bar_label(bars, labels=values)

        plt.yticks(y_pos, projects)
        plt.xlabel("Link Change Set Percentage (%)")
        plt.title("Project vs Trace Link Coverage")

        plt.gca().invert_yaxis()  # biggest on top

        plt.tight_layout()
        plt.show()
    else:
        plt.figure(figsize=(14, 6))

        x_pos = range(len(projects))

        bars = plt.bar(x_pos, values)

        plt.bar_label(bars, labels=[f"{v:.2f}" for v in values])

        plt.xticks(x_pos, projects, rotation=45, ha="right")

        plt.ylabel("Link Change Set Percentage (%)")
        plt.xlabel("Project")
        plt.title("Project vs Trace Link Coverage")

        plt.tight_layout()
        plt.show()

# ---------------------------------------------------
# Stats Utilities
# ---------------------------------------------------

def commits_to_issues():
    """
    Counts the number of commits that have 1, 2, 3,...., n linked issues
    """

    from db import init_db, SEOSS33
    projects = init_db()
    counts = {}
    for project in projects:
        db = SEOSS33(project)
        links = db.get_trace_links()

        for _, issues in links:
            counts.setdefault(len(issues), 0) 
            counts[len(issues)] += 1
        db.close()

    print(f"No. of issues | commits")
    for length, count in sorted(counts.items(), key=lambda x:x[0]):
        print(f"{length:>13} | {count:<7}")